### ISSUE TITLE
Change of name of color layer

### ISSUE THREAD

**Issue by ahuk** [odmln/sketch-feather#2]
The name currently is: Icon 🎨
Issue is that his is actually the pulldown for the `color`, not the `icon`. 

![screen_shot_2018-02-15_at_17_57_03](https://user-images.githubusercontent.com/514732/36270088-28ef0502-127b-11e8-97ba-251034bced00.png)

The emoji is hard to read IMHO.

**Comment by odmln** [comment]
@ahuk I had used an Emoji because Override Labels get truncated. I tried to keep the label short. I'll find a workaround for this and make it clearer. Stay tuned.

**Comment by alexcamlo** [comment]
IMHO, I do also use the emoji for color palette to Color dropdowns.
I'm for one at leaving it how it is.

**Comment by ahuk** [comment]
@thewinger don't you think that the color palette icon is pretty hard to read?

**Comment by alexcamlo** [comment]
I'm not objective because is the icon I use in all my sketch documents for Color in the symbols overrides.

**Comment by odmln** [comment]
@ahuk @thewinger I will change it to pure text in my next release. Sketch 49 just updated and now puts Override text on it's own line so nothing gets truncated. No more need for shortened text or an emoji.

**Comment by ahuk** [comment]
@odmln I would still strongly suggest to call it "color" as the first glance impression is "Icon"

**Comment by odmln** [comment]
Label has been changed to Icon Color. Going to close this.
