### ISSUE TITLE
Only color artboards should appear here ideally

### ISSUE THREAD

**Issue by ahuk** [odmln/sketch-feather#3]
The overrides pulldown shows this

![screen shot 2018-02-15 at 17 56 25](https://user-images.githubusercontent.com/514732/36270123-3c819af8-127b-11e8-9514-26f7b4c0edf6.png)

**Comment by odmln** [comment]
@ahuk you are correct. The fix for this requires me to resize the color artboards to a different size than the icon artboards. Sketch believes they are equal currently. Will push a fix for this shortly. Thanks!

**Comment by alexcamlo** [comment]
I have added a PR with this changed.
